apiVersion: kuma.io/v1alpha1
kind: MeshPassthrough
metadata:
 name: allow-some-passthrough
 namespace: kuma-system
 labels:
   kuma.io/mesh: demo
spec:
 targetRef:
   kind: MeshSubset
   proxyTypes:
   - Sidecar
   tags:
     kuma.io/service: netshoot_httpbin_svc_80
 default:
   passthroughMode: Matched
   appendMatch:
   - type: Domain
     value: '*.com'
     protocol: tls
     port: 443
   - type: Domain
     value: '*.io'
     protocol: tls
     port: 443