apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
 name: httpbin-https
 namespace: kuma-system
 labels:
   kuma.io/mesh: demo
spec:
 match:
   type: HostnameGenerator
   port: 80
   protocol: http
 endpoints:
 - address: httpbin.org
   port: 443
 tls:
   enabled: true
   verification:
     serverName: httpbin.org
