# Create a namespace to deploy the httpbin service
---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    kuma.io/mesh: demo
    kuma.io/sidecar-injection: enabled
spec: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
spec:
  ports:
  - port: 80
    appProtocol: http
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: netshoot
  namespace: httpbin
spec:
  ports:
  - port: 80
    appProtocol: http
    targetPort: 80
  selector:
    app: netshoot
---
#Deploy netshoot to test the httpbin service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sleep", "inf"]
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
