apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: metrics-default
  namespace: kuma-system
  labels:
    kuma.io/mesh: demo
spec:
  default:
    sidecar:
      includeUnused: true
    backends:
    - type: Prometheus
      prometheus:
        clientId: main-backend
        port: 5670
        path: "/metrics"
        tls:
          mode: Disabled
