apiVersion: kuma.io/v1alpha1
kind: MeshPassthrough
metadata:
 name: allow-some-passthrough
 namespace: kuma-system
 labels:
   kuma.io/mesh: demo
   kuma.io/origin: zone
spec:
 targetRef:
   kind: Mesh
   proxyTypes:
   - Sidecar
 default:
   passthroughMode: Matched
   appendMatch:
   - type: Domain
     value: 'httpbin.org'
     protocol: tls
     port: 443